"""empty message

Revision ID: 34d30170a21d
Revises: c4bffc6ef6b0
Create Date: 2025-01-27 15:50:37.676416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d30170a21d'
down_revision: Union[str, None] = 'c4bffc6ef6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###
